[build]
builder = "NIXPACKS"
buildCommand = "cd vew-backend && rm -rf node_modules .next && npm install"

[deploy]
startCommand = "cd vew-backend && npm start"
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10
